package com.qf.application.dao;


import com.qf.application.model.User;

import java.util.List;
import java.util.Map;

public interface IUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    int insert(com.qf.application.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    int insertSelective(com.qf.application.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    com.qf.application.model.User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    int updateByPrimaryKeySelective(com.qf.application.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 09 21:11:41 CST 2019
     */
    int updateByPrimaryKey(com.qf.application.model.User record);

    List<User> getListPage(Map<String, Object> paramMap);

    int queryUserTotal(Map<String, Object> paramMap);
}